# Generated by Django 3.2.4 on 2021-08-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210823_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_book',
            name='issued_on',
        ),
    ]
